### ISSUE TITLE
New error: "WARNING: could not determine DPI"

### ISSUE THREAD

**Issue by andrez4vz** [camenduru/3d-photo-inpainting-colab#3]
Hello, I get this error. Can you tell me if because I did something wrong or the problem is the code?

`/content/3d-photo-inpainting
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
running on device 0
  0% 0/1 [00:00<?, ?it/s]Current Source ==>  357430721_816222763207823_4868344721665083094_n
...
	 processing patch 94 | [923   0 246 246]
	 processing patch 95 | [1108    0  246  246]
	 processing patch 96 | [1200    0  246  246]
	 processing patch 97 | [1292    0  246  246]
finished
Start Running 3D_Photo ...
Loading edge model at 1690210878.4564593
Loading depth model at 1690210882.7472916
Loading rgb model at 1690210883.9680858
Writing depth ply (and basically doing everything) at 1690210885.2083888
Writing mesh file mesh/357430721_816222763207823_4868344721665083094_n.ply ...
Making video at 1690211112.8314586
fov: 53.13010235415598
WARNING: could not determine DPI
Killed`

**Comment by JeffDengNF** [comment]
I face the same error, it seems somthing went wrong about the code recently, I run the code successfully about 1 month ago.

**Comment by QOO211** [comment]
Me, too. The same Error.
WARNING: could not determine DPI
Killed

**Comment by JeffDengNF** [comment]
It seems only the depth can be output but not the videos.

**Comment by camenduru** [comment]
thanks for the info ❤ please try again

**Comment by JeffDengNF** [comment]
> thanks for the info ❤ please try again

Thanks for your effort, It works now, Your work realy promotes our research works.
